# Generated by Django 3.2.5 on 2021-07-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_project', models.CharField(max_length=255)),
                ('languaje', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('type_project', models.CharField(max_length=50)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='educ_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_info', models.CharField(max_length=100)),
                ('name_info', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.personal_info')),
            ],
        ),
    ]
